name: Setup Node.js for CI/CD
description: Setup Node.js for CI/CD

inputs:
    node-version:
        description: "Node.js version"
        required: false
        default: "26"

runs:
    using: "composite"
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
              node-version: ${{ inputs.node-version }}

        - name: Install dependencies
          shell: bash
          run: |
              npm ci
